# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lwidmer <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/06 15:02:43 by lwidmer           #+#    #+#              #
#    Updated: 2023/06/07 11:12:01 by lwidmer          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

mega:
	c++ -Wall -Werror -Wextra -std=c++98 megaphone.cpp -o megaphone

mega2:
	rm megaphone ; c++ 2_megaphone.cpp -o megaphone
